# **Healthcare Service Utilization Analysis Using Python**

### **Project Objectives**

* To identify the most utilized healthcare service categories across
California between 2021 and 2023.
* To compare healthcare service utilization across different insurance payer types to understand variations in service demand.
* To analyze demographic and regional variations in healthcare service utilization based on age group, assigned sex at birth, county, and Covered California region.
* To evaluate insurance coverage patterns by analyzing medical coverage months across different payer types and geographic regions.
* To identify healthcare utilization trends over the period 2021–2023 and examine changes in service demand across different healthcare service categories.
* To generate actionable insights that support healthcare planning, resource allocation, and data-driven decision-making.

### **Dataset Information**

Source: California Health and Human Services (CalHHS) – Healthcare Payments Data (HPD) Services Report

Location: California, USA

Year/Timeline: 2021–2023 (Filtered from the original dataset covering 2018–2023)

Domain: Healthcare Analytics

In [1]:
#IMPORTING LIBRARY
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
#DATA LOADED FROM THE LOACL DRIVE
from google.colab import files
uploaded = files.upload()

Saving services_rpt_data-service-category.csv to services_rpt_data-service-category.csv

In [3]:
#Csv file is converted to datafarme with pandas
df = pd.read_csv("services_rpt_data-service-category.csv")

# **Initial Inspection / Initial EDA**

In [4]:
# Displaying first 5 rows
df.head()

,reporting_year,age_band,assigned_sex_at_birth,county_name,county_name_plus_spa,covered_california_region,payer_type,service_category,member_count,medical_coverage_months,service_count,suppression_ind
0,2018,0-17,Female,Alameda,Alameda,Alameda County,Commercial,Anesthesia,970.0,871724.0,1132.0,N
1,2018,0-17,Female,Alameda,Alameda,Alameda County,Commercial,DME,2480.0,871724.0,4496.0,N
2,2018,0-17,Female,Alameda,Alameda,Alameda County,Commercial,E&M,65138.0,871724.0,258239.0,N
3,2018,0-17,Female,Alameda,Alameda,Alameda County,Commercial,Imaging,11741.0,871724.0,20779.0,N
4,2018,0-17,Female,Alameda,Alameda,Alameda County,Commercial,Other,3773.0,871724.0,4872.0,N

In [5]:
# To evaluate data health, check for missing values, and monitor memory consumption.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120960 entries, 0 to 120959
Data columns (total 12 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   reporting_year             120960 non-null  int64
 1   age_band                   120960 non-null  object
 2   assigned_sex_at_birth      120960 non-null  object
 3   county_name                120960 non-null  object
 4   county_name_plus_spa       120960 non-null  object
 5   covered_california_region  120960 non-null  object
 6   payer_type                 120960 non-null  object
 7   service_category           120960 non-null  object
 8   member_count               107956 non-null  float64
 9   medical_coverage_months    107956 non-null  float64
 10  service_count              107956 non-null  float64
 11  suppression_ind            120960 non-null  object
dtypes: float64(3), int64(1), object(8)
memory usage: 11.1+ MB

In [6]:
#To understand the attribute and to check  the column labels
df.columns

Index(['reporting_year', 'age_band', 'assigned_sex_at_birth', 'county_name',
       'county_name_plus_spa', 'covered_california_region', 'payer_type',
       'service_category', 'member_count', 'medical_coverage_months',
       'service_count', 'suppression_ind'],
      dtype='object')

In [7]:
#To understand quick statistical summary of your DataFrame
df.describe()

       reporting_year   member_count  medical_coverage_months  service_count
count   120960.000000  107956.000000             1.079560e+05   1.079560e+05
mean      2020.500000    5141.489987             1.700362e+05   2.493505e+04
std          1.707832   12081.229190             3.125355e+05   7.158930e+04
min       2018.000000       0.000000             0.000000e+00   0.000000e+00
25%       2019.000000     195.000000             7.691000e+03   5.580000e+02
50%       2020.500000     884.000000             3.399700e+04   2.958000e+03
75%       2022.000000    3957.250000             1.741990e+05   1.529525e+04
max       2023.000000  146880.000000             2.128166e+06   1.935875e+06

In [8]:
#Checking the datatypes
df.dtypes

reporting_year                 int64
age_band                      object
assigned_sex_at_birth         object
county_name                   object
county_name_plus_spa          object
covered_california_region     object
payer_type                    object
service_category              object
member_count                 float64
medical_coverage_months      float64
service_count                float64
suppression_ind               object
dtype: object

In [9]:
#Finding The Duplicate Values
df.duplicated().sum()

np.int64(0)

In [10]:
#Finding The Empty Cells
df.isnull().sum()

reporting_year                   0
age_band                         0
assigned_sex_at_birth            0
county_name                      0
county_name_plus_spa             0
covered_california_region        0
payer_type                       0
service_category                 0
member_count                 13004
medical_coverage_months      13004
service_count                13004
suppression_ind                  0
dtype: int64